fgap : 1 # frequency gap [Hz] (also define the lenght of the cavity)
fmin : 0 # starting mod [Hz]
modes : 30 # number of modes
gain_distrib : "gauss(v,50,10)" # will be evaluated by python with "v" as the frequency. Numpy is importad without prefix (sqrt() -> numpy.sqrt())

display_modes: 10