fgap : 1          # frequency gap [Hz] (also define the lenght of the cavity)
modes : 100       # number of modes
display_modes: 10

# The following parameters will be evaluated by python with "i" as the mode number and "v" as the frequency of the mode i.
# /!\ Modes are starting from 1 and goes to modes
# Numpy is imported without prefix (numpy.sqrt() -> sqrt())
phase_distrib:     "0"
amplitude_distrib: "1"              # arbitrary unit
gain_distrib :     "gauss(v,50,20)" # arbitrary unit